server:
  port: 18001

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://118.190.97.96:3306/test?useSSL=false
    username: 
    password: 
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    database: 0   
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes:
        - 118.190.97.96:7001
        - 118.190.97.96:7002
        - 118.190.97.96:7003
        - 118.190.97.96:7004
        - 118.190.97.96:7005
        - 118.190.97.96:7000